version: '3.8'

services:
  app:
    image: todo-app-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:3000
    container_name: todo-app-frontend-dev
