version: '3.8'

services:
  app:
    image: todo-app-frontend-dev
    build:
      context: ./todo-frontend/
      dockerfile: Dockerfile.dev
    volumes:
      - ./todo-frontend/:/usr/src/app
    ports:
      - 3001:3000
    container_name: todo-app-frontend-dev
  nginx:
    image: nginx:1.25.3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
